# Generated by Django 3.1.7 on 2022-08-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burntype', models.CharField(max_length=10)),
                ('content', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='BurnPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burntype', models.CharField(choices=[('열탕화상', '열탕화상'), ('저온화상', '저온화상'), ('마찰화상', '마찰화상'), ('접촉화상', '접촉화상'), ('화학화상', '화학화상'), ('흡입화상', '흡입화상'), ('전기화상', '전기화상'), ('햇빛화상', '햇빛화상'), ('화염화상', '화염화상'), ('증기화상', '증기화상')], default='열탕화상', max_length=4)),
            ],
        ),
    ]
