# Generated by Django 3.1.7 on 2022-08-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wound', '0002_burninfo_burnpic_picktype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PickType',
        ),
    ]
